### ISSUE TITLE
Ask for the code of word embedding

### ISSUE THREAD

**Issue by edwarddiou** [GRAPH-0/RGTN-NIE#3]
Thanks for open source of EST task, it help me a lot.
I try to use this model for my own datasets, but I got some problem about the embedding process...
May I ask for the code that show graph and text in this paper?  
thank you !

**Comment by GRAPH-0** [comment]
@edwarddiou 

Some code examples for the embedding process :
- [Example codes](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/node2vec.html) from pytorch geomectric and [the github repo](https://github.com/aditya-grover/node2vec) for graph structure embedding using node2vec.   
- Text embeddings are obtained by [Transformer-XL](https://github.com/huggingface/transformers). For details of processing, please refer to [this](https://github.com/acbull/GPT-GNN/blob/8ac50bf0720e5260b175f55e338c09e3a3adf729/example_OAG/preprocess_OAG.py#L58).
