### ISSUE TITLE
Question about input data format

### ISSUE THREAD

**Issue by sungjune-kim** [GRAPH-0/RGTN-NIE#4]
Hi, I followed the tutorial and ran 'sh train_geni.sh' in my terminal but it returned 'FileNotFoundError: [Errno 2] No such file or directory: 'datasets/fb15k_rel.pk''. Can you help me?

**Comment by GRAPH-0** [comment]
This looks to be a file path problem.
First, check if the processed feature file "fb15k_rel.pk" is downloaded from Google Drive and then placed in "RGTN-NIE/datasets".
If the above still doesn't work, you can try specifying the absolute path to that file using the arg "--data_path".
