### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Syzseisus** [GRAPH-0/RGTN-NIE#9]
Hi. First of all, I really appreciate to your wonderful work and code.

I open this issue to ask question:
> How did you define node feature of each datasets?

Sincerely,
Wooseong Cho.

**Comment by GRAPH-0** [comment]
Hi @Syzseisus .
Thanks for your interest!
We extract node structural features using the node2vec and node semantic features using Transformer-XL.
Refer to Paper:
<img width="727" alt="image" src="https://github.com/GRAPH-0/RGTN-NIE/assets/85398576/b80d9d2c-2214-4b42-bc5b-f23a53161efc">

**Comment by Syzseisus** [comment]
Thank you for your quick response.

I've already reviewed the provided resources.  
However, I'm interested in obtaining a detailed understanding of the configuration settings for  
`node2vec` and `Transformer-XL` models.  
Could you please provide me with the specific parameters or something?

ALTERNATIVELY, for FB15k, I would appreciate it if you could confirm whether the order of nodes in the pickle file provided in Google Drive is the same as in the `dgl`.
If you are unsure, please let me know the order
or you can check it by following these steps:
1. For the order of nodes used in `dgl`, you can access the raw tgz file from [here](https://data.dgl.ai/FB15k.tgz)  
    and find the order in the `entities.dict` file.
2. However, please note that 0`dgl` uses the node entity name as a hash.
    To find the real names of the nodes, you can refer to the [`entities2wikidata.json`](https://github.com/villmow/datasets_knowledge_embedding/blob/master/FB15K/entity2wikidata.json) file.
    
Thank you for your assistance.
    
Sincerely,
Wooseong Cho.

**Comment by GRAPH-0** [comment]
Hi,

1. For node embedding, you can refer to #3 and #6.

The `node2vec` settings:
* FB and tmdb:
```python
model = Node2Vec(data.edge_index, embedding_dim=64, walk_length=20,
                     context_size=10, walks_per_node=10, num_negative_samples=1,
                     p=1, q=1, sparse=True).cuda()
loader = model.loader(batch_size=128, shuffle=True, num_workers=4)
optimizer = torch.optim.SparseAdam(list(model.parameters()), lr=0.01)
```

* imdb:
``` python
model = Node2Vec(data.edge_index, embedding_dim=128, walk_length=20,
                     context_size=10, walks_per_node=10, num_negative_samples=1,
                     p=1, q=1, sparse=True).cuda()
```
 
2. Sorry, I fail to open the tgz file from `dgl` to check the order. But you can get the correspondence between node id and mid from `datasets/FB15k/fb15k_description.tsv`. I think this can help you!

Sincerely,
Han
